"""empty message

Revision ID: eab0ff1efbcc
Revises: 5bc5bcfbeaba
Create Date: 2024-02-09 00:28:26.145341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab0ff1efbcc'
down_revision: Union[str, None] = '5bc5bcfbeaba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
